@extends('support.layout')
     @section('content')
     <section class="relative  mx-auto w-full max-w-7xl text-gray-900">
       <div class="container">
        <div class="flex flex-wrap -mx-5 mt-0">
            <div class="w-full px-5 mt-0">
                <div class="bg-gray-200 py-20  px-10">
                    <div class="px-10">
                        <p class="text-2xl font-semibold">PLEASE READ THE TERMS AND CONDITIONS BELOW CAREFULLY.</p>
                        <h3 class="font-bold text-xl mt-4">TERMS ACCEPTANCE</h3>
                        <p class="mt-4">Chatboat (Hereinafter Referred to as “platform”/ “mobile Application”) is a Website and
                            Mobile-based Client Communication Integration Platform Owned and Operated by Vd Infomedia Pvt.
                            Ltd. Having Office at B 507 World Trade Tower, Makarba, Sg Highway, Ahmedabad (Hereinafter
                            Referred to as “infomedia”/ “we”/ “us”/ “our”).</p>
                            <p>This Document Represents a Legally Binding Agreement Between Any Registered or Unregistered User
                                of the Platform (Referred to as "You," "Your," or "User") and Us. It Outlines the Terms and
                                Conditions Governing Your Access and Usage of the Platform, as Well as Our Associated Websites,
                                Services, Applications, Products, and Content (Collectively Referred to as the "Services").</p>
                            <p>The Terms and Conditions Stated in This Document Will Become Effective Once You Accept Them. You
                                Can Provide Your Acceptance Directly or Indirectly in Electronic Form by Clicking on the "I
                                Agree" Button or by Using the Platform. Additionally, Creating a Registered Account on the
                                Platform (Referred to as an "Account") Implies Your Acceptance of These Terms. They Will Govern
                                the Relationship Between You and Us Regarding Your Usage of the Platform and the Services
                                Provided Therein.</p>
                            <p>This Document is Considered an Electronic Record as Per the Information Technology Act, 2000, and
                                the Relevant Rules Framed Under It, Along With the Amended Provisions Related to Electronic
                                Records in Various Statutes as Amended by the Information Technology Act, 2000. It Should Be
                                Noted That This Electronic Record is Generated by a Computer System and Does Not Require Any
                                Physical or Digital Signatures.</p>
                            <p>Please Be Aware That This Document is Not Published by the Provisions of the General Data
                                Protection Regulation 2016/679 ("Gdpr"). Therefore, if You Are a Resident of the European Union
                                ("Eu"), You Acknowledge That Our Services Are Not Extended to Eu Territories. Additionally, We
                                Do Not Represent or Warrant That We Are Gdpr Compliant.</p>
                            <p>Please Carefully Read This Document. By Using the Platform and Our Services, You Indicate That
                                You Understand, Agree, and Consent to the Terms Stated in This Document. If You Do Not Agree
                                With These Terms, Please Refrain From Using This Platform. By Using the Platform and Its
                                Services, You Unconditionally Consent and Agree, as Outlined in Section 43a and Section 72a of
                                the Information Technology Act, 2000, to Allow Us to Access and Use the Personal Information
                                That You Have Voluntarily Provided to Us in Connection With the Use of the Platform and Its
                                Services.</p>
                            <p>By providing us with your information or utilizing the platform and its services, you give your
                                consent to the collection, storage, processing, and transfer of both personal information (as
                                defined in our privacy policies) and non-personal information by us, as specified in this
                                document. Furthermore, you agree that such collection, use, storage, and transfer of information
                                will not cause any loss or wrongful gain to you or any other individual.</p>
                            <p>Please note that these Terms of Use and the services provided by us are intended for
                                organizations, entities, companies, and legal persons. Individuals who qualify as consumers,
                                meaning natural persons engaging in activities outside the scope of economic activities and for
                                purposes unrelated to trade, business, craft, or profession, are excluded.</p>
                            <p>To access and use this platform, you must be at least eighteen (18) years old. Minors, i.e.,
                                individuals below the age of 18, are not permitted to avail themselves of the services provided
                                on this platform. The entity or organization on whose behalf you access the platform and utilize
                                the services should be incorporated by applicable laws.</p>
                            <p>If you are using the services as an employee, agent, or contractor of a corporation, partnership,
                                or similar entity, you represent and warrant that you have the authority to sign for and bind
                                such entity to accept these Terms of Use.</p>
                            <p>Your access to the platform and utilization of our services are also governed by our Privacy
                                Policy, which you can find directly on the platform. The terms of the privacy policies, both
                                before and after signing up, are incorporated herein by reference. You agree that all
                                agreements, notices, disclosures, and other communications we provide to you electronically
                                fulfil any legal requirement for written communication.</p>
                            <p>Before using, subscribing to, or participating in the platform, it is understood and warranted
                                that you, as the user, have fully read, understood, and accepted the Terms of Use. These terms
                                may be updated from time to time without prior notice to you. It is recommended that you
                                periodically review these Terms of Use for any updates. We will make reasonable efforts to
                                notify you of any amendments to the Terms of Use through a notice on the platform. Your
                                continued access to the platform and/or use of the services following the update of the Terms of
                                Use will be considered as your acceptance of the updated terms. If you do not agree with or wish
                                to be bound by the updated Terms of Use, you may not access or use the platform or the
                                services.We may occasionally release new versions of the platform or introduce new services,
                                which will be subject to these Terms of Use and any additional terms of service applicable to
                                such new versions or services.</p></br>
                                <h3 class="text-xl font-semibold">
                                    CHATBOAT SERVICES
                                </h3>
                                
                            <p>The platform provides users who have subscribed to our subscription plan with access to secure
                                and user-friendly virtual software that operates in the cloud. This software facilitates the
                                integration of all client communications into one platform, utilizing the WhatsApp Business API.
                                These services are referred to as "Chatboat Services." You acknowledge and agree that the
                                Platform relies on the WhatsApp Business API to deliver the Chatboat Services. Therefore, any
                                modifications made to the WhatsApp Business API may impact or even prevent us from providing
                                Chatboat Services. The Platform has no control over the delivery of services by the WhatsApp
                                Business API or its technical configuration.</p>
                            <p>Please note that the Chatboat Services are exclusively intended for business use or internal
                                business purposes within the entity or organization represented by the users. They should not be
                                used for personal or household purposes. The Chatboat Services must be utilized for their
                                intended purposes and objectives. Additionally, users are responsible for ensuring their own
                                access to the internet and acquiring the necessary equipment to utilize the Chatboat Services.
                            </p>
                            <p>The Chatboat Services encompass various features, including but not limited to:</p>
                            <h5 style="font-weight:600">1) Chatbot:</h5>
                            <p>By installing the Chatboat WhatsApp Chatbot, you can create a digital assistant for yourself or
                                your entity/organization. This enables you to provide automated responses to customer queries.
                            </p>
                            <h5 style="font-weight:600">2) Multiple Agents:</h5>
                            <p> If your subscription plan includes the WhatsApp workspace feature, you are entitled to add
                                multiple agents (such as employees, colleagues, etc.) to the WhatsApp workspace, as permitted by
                                your subscription plan. These agents will have access to the workspace.</p>
                            <h5 style="font-weight:600">3) Private Notes:</h5>
                            <p>Authorized employees can add private notes to conversations and contacts. These private notes
                                restrict or provide access to the information within your entity or organization, ensuring
                                confidentiality.</p>
                            <h5 style="font-weight:600">4) Sharing Contents:</h5>
                            <p>You can create and share various types of content, including text messages, images, videos,
                                locations, contacts, audio files, and more ("Your Content"). This allows you to share relevant
                                information with your clients and others.</p>
                            <h5 style="font-weight:600">5) WhatsApp Message Templates:</h5>
                            <p>You can create customized WhatsApp Message Templates, as defined in the WhatsApp documentation.
                                However, these templates require approval from WhatsApp. Additionally, you are responsible for
                                any applicable pricing associated with the WhatsApp Message Templates and must make the
                                necessary payments to Chatboat for their usage. WhatsApp Template Messages refer to specific
                                message formats that have been reviewed and approved by WhatsApp for businesses to send messages
                                to their customers. Starting from 1st February 2022, WhatsApp has implemented conversation-based
                                pricing, which can be found at the following link: URL to pricing details.</p></br>
                            <h3 class="text-xl font-semibold">
                                SIGN-UP AND ACCOUNT REGISTRATION PROCESS
                            </h3>
                           
                            
                            <p>If you wish to avail the Chatboat Services, please follow the steps below to sign up:</p>
                            <p>1. Visit our Platform's website at https://Chatboat.com ("Website").</br>
                                2. Provide your work email address and active mobile number on the Website to register for a
                                free trial.</br>
                                3. After providing your work email and mobile number, you will be redirected to our Sandbox
                                account. You will be prompted to link your WhatsApp number with our shared Sandbox number to
                                access the features of Chatboat Services for your business.</br>
                                4. We will request certain information from you and your business, including:</br>
                                - Name of your entity or organization/yourself</br>
                                - The registered address of your entity/yourself</br>
                                - Purpose of the entity</br>
                                - Website of your entity</br>
                                - Business Category</br>
                                - Contact number, and more.</br>
                                5. You will need to apply for the WhatsApp Business API, powered by a specific Business Service
                                Provider, directly through the Chatboat portal. You can choose assisted onboarding from our
                                Chatboat onboarding team, who will provide the necessary assistance and demos to help you
                                onboard your business with Chatboat.</br>
                                6. After the demos of Chatboat Services, if you decide to sign up, we will send you a Chatboat
                                Onboarding Guide in the form of a Google Form. This Guide will request information about your
                                organization/business, including business incorporation documents, utility bills, social media
                                credentials, and the WhatsApp number to be integrated with the Platform, among others. This
                                information is collectively referred to as "Registration Data."</br>
                                7. You are required to complete the Guide and agree to the Terms of Use and the relevant terms
                                and conditions of WhatsApp Business. We will share the Guide with WhatsApp for review and
                                approval.</br>
                                8. Once the Guide is reviewed and verified by WhatsApp, the phone number you provided will be
                                approved by WhatsApp to use their WhatsApp Business API services. Upon approval, we will send an
                                OTP and a sign-up link to your WhatsApp number as provided in the Guide.</br>
                                9. Using the sign-up link, you can create an Account as specified in clause 4 below to access
                                the Chatboat Services.</br>
                                Please note that all the necessary steps and instructions for signing up and accessing the
                                Chatboat Services will be provided to you in a clear and organized manner.
                            </p></br>
                            <h3 class="text-xl font-semibold">
                                ACCOUNT REGISTRATION AND ACCOUNT MAINTENANCE
                            </h3>
                            <p>Once you click on the sign-up link provided, you will be redirected to the Website. To access and
                                use the Chatboat Services on the Platform, you will need to create an Account. Follow the
                                prompts on the Platform to register and provide the required information. Upon completing the
                                registration process, you will receive a username and password (Login Credentials) for your
                                Account.</p>
                            <p>During the registration, you will be asked to provide certain information about your
                                organization. As the creator of the Account, you confirm that you are duly authorized to
                                represent and sign on behalf of the entity mentioned in the Account. The information provided
                                should be accurate, complete, and not misleading. By accepting these Terms of Use, the entity
                                named in the Account agrees to its terms. These Terms of Use will be effective from the date of
                                Account creation and verification. Please ensure that you promptly update any changes to the
                                provided information to ensure effective communication with us. If any Registration Data
                                provided by you is found to be untrue, inaccurate, not current, or incomplete, we reserve the
                                right to suspend, terminate, or block access to your Account on the Platform.</p>
                            <p>During the Account creation process, you agree to:</br>
                                - Keep your password and login information restricted and do not share it with any unauthorized
                                person or entity.</br>
                                - Not to use the name or email of another person without proper authorization.</br>
                                - Not to use an email or profile name that is profane, offensive, or inappropriate.</br>
                                - Not to allow any third party to use your login information, Registration Data, or
                                Account.</br>
                                - To promptly notify us of any activities in your Account, even if such activities are not
                                committed by you.
                            </p>
                            <p>We may periodically modify or add information fields required for Account creation. You agree to
                                promptly complete any additional or modified information fields requested by us. In some cases,
                                you may also need to update your Account and/or operating system settings to allow us access to
                                other details such as the address book/contacts and enable geolocation, camera, and microphone
                                functions. Your registration with us is subject to our confirmation, and your Account will
                                become valid once we confirm your registration or activate your Account.</p>
                            <p>We reserve the right to use your Registration Data for servicing and operating the Platform, as
                                described in more detail in this Terms of Use and our Privacy Policies.</p></br>
                            <h3 class="PASSWORD & SECURITY
                            ">
                                PASSWORD & SECURITY
                            </h3>
                            <p>Maintaining the confidentiality of your login credentials is of utmost importance. You must
                                refrain from disclosing or sharing them with any third party. It is your responsibility to
                                prevent unauthorized usage of your login credentials. If, under any circumstances, you suspect a
                                breach of security, such as the disclosure, theft, or unauthorized use of your identification,
                                it is imperative that you promptly notify us. If we have reasonable grounds to believe that your
                                identification is being misused in a manner that contravenes the terms of use, we reserve the
                                right to temporarily suspend your access privileges. We will provide you with notice of this
                                suspension and prohibit access from your identification until the matter is resolved.</p></br>
                            <h3 class="THIRD-PARTY COMMUNICATIONS
                            ">
                                THIRD-PARTY COMMUNICATIONS
                            </h3>
                            <p>During the registration process for your account on our platform, you will be required to provide
                                us with your contact details, including your email address. By doing so, you are explicitly
                                permitting us to use your email address for essential service notifications, important
                                announcements, and other administrative communications about your use of the platform.
                                Additionally, you may also receive marketing and advertising communications from us and our
                                third-party advertising partners.</p>
                            <p>While you have the option to opt out of receiving certain notifications, please note that there
                                are certain services and administrative notifications from which you cannot opt-out. If you do
                                not wish to receive any platform-related notifications, the only available course of action is
                                to cease using the platform and delete your account.</p>
                            <p>It is important to understand that we cannot be held liable for any communications you receive
                                directly or indirectly from third parties in connection with the platform. Any actions you take
                                or choose to refrain from taking as a result of such third-party communications are your own
                                responsibility. We also do not assume any responsibility for verifying the identity or
                                trustworthiness of the source or content of any third-party communications.</p></br>
                            <h3 class="text-xl font-semibold">
                                ACCOUNT DELETION & TERMINATION OF PLATFORM ACCESS
                            </h3>
                            <p>We maintain the right to disable your account under the following circumstances:</p>
                            <p>1) Failure to comply with the provisions outlined in these Terms of Use and/or WhatsApp Business
                                Policies.</br>
                                2) Activities on your account that, at our sole discretion, may cause harm to us, the platform,
                                or impair the services. This includes actions that infringe upon or violate the rights of third
                                parties or any applicable laws or regulations.</br>
                                3) Engaging in conduct that we deem inappropriate or unacceptable in our sole discretion.</br>
                                4) Failure to clear subscription or usage fees.</br>
                                5) Any other reasons determined by us.
                            </p>
                            <p>We may also disable your account or suspend/terminate your access to the platform if you file a
                                claim against us or involve the platform in any claim. In such cases, we reserve the right to
                                pursue any available remedies as per applicable laws and regulations. Disabling your account or
                                suspending/terminating your access to the platform does not waive our rights or claims arising
                                from your breach of these Terms of Use or any other acts or omissions on your part.
                                If your right to use the platform is terminated, limited, or suspended, these Terms of Use will
                                continue to be in effect and enforceable.</p>
                            <p>Without our prior written consent, you are not permitted to register or create a new account
                                using your name, a fake or borrowed name, or the name of any third party, even if you are acting
                                on behalf of that third party.</p>
                            <p>You have the option to terminate your account at any time by sending a request via email to
                                team@Chatboat.com. Upon receiving the termination request, we will review your account for any
                                pending subscription fees. Only after completing this review will we proceed with terminating
                                the account from the platform. However, please note that we reserve the right to retain your
                                registration data in an anonymous form and any other information provided on an "as-is" basis as
                                required by law.</p>
                            <p>Notwithstanding anything mentioned in these Terms of Use, any clauses that, by their nature,
                                should survive the expiration or termination will continue to be fully effective even after the
                                expiration or termination of these Terms of Use.</p></br>
                            <h3 class="text-xl font-semibold">
                                YOUR CONSENT
                            </h3>
                            <p>You acknowledge and provide your full and unconditional consent to the following:</p>
                            <p>1) Your account information is permanently stored in a computer database that is owned,
                                maintained, and controlled by us.</br>
                                2) Your account information is being shared with any third-party entity that enters into a
                                commercial relationship with us.</br>
                                3) Your account information is being shared in its original form or an aggregated form with
                                other third-party entities.</br>
                                4) Your account information is being shared with our partners, licensors, and affiliates.</br>
                                5) Receiving links to third-party websites and services, as well as displaying advertisements
                                for third-party service providers that have established a commercial relationship with us. These
                                are collectively referred to as "Third-Party Links & Advertisements."</br>
                                6) Receiving telephone calls and text messages from us regarding our services, including
                                promotional calls and messages, as well as updates to our products. This will be done if you
                                provide your mobile contact number or any other contact information while creating an account or
                                interacting with us.
                            </p></br>
                            <h3 class="text-xl font-semibold">
                                SUBSCRIPTION PLAN:
                            </h3>
                            <p>To access Chatboat services, users must select an appropriate plan from the available
                                subscription plans listed on the platform's pricing page ( https://chatboat.in/chatboat/#pricing
                                ) and agree to pay the corresponding fee mentioned in the chosen plan ("Subscription Fee"). The
                                Subscription Fee must be paid by the user on a monthly, quarterly, half-yearly, or annual basis
                                within seven (7) days from the invoice date. The subscription to Chatboat services will renew
                                automatically unless the account is terminated, or the user provides a written notice of
                                non-renewal at least thirty (30) days before the expiration of the current subscription term.
                                Please note that the subscription plan chosen by the user may be updated periodically, and it is
                                our responsibility to notify you of such changes. Payment obligations are non-cancelable,
                                regardless of your utilization of the services, and except as expressly permitted in these Terms
                                of Use, the Subscription Fee paid is non-refundable.
                            </p>
                            <p>We provide payment authorization on our platform through the following payment services:</br>
                                - Razorpay</br>
                                - Stripe
                            </p>
                            <p>You can make payments using the following methods through the aforementioned payment
                                services:</br>
                                - Credit Cards: Domestic and International Visa, MasterCard, and American Express credit
                                cards.</br>
                                - Debit Cards</br>
                                - Net banking</br>
                                - UPI
                            </p>
                            <p>If undisputed Subscription Fee(s) remains overdue for more than thirty (30) days, we may, upon
                                written notification, suspend your access to the platform, including your account, until the
                                unpaid Subscription Fee(s) are paid in full.</p>
                            <p>Please note that the Subscription Fee does not include any taxes, levies, duties, or similar
                                governmental assessments, such as value-added, sales, use, or withholding taxes, imposed by any
                                local, state, provincial, or foreign jurisdiction ("Taxes"). You agree to pay applicable direct
                                or indirect Taxes associated with your purchases under this agreement, and if legally required,
                                we will itemize the taxes on the invoice.</p>
                            <p>The Subscription Fee does not cover any charges imposed by WhatsApp Business API for Template
                                Messages or Conversations. We will raise an invoice based on the usage of messages/conversations
                                every month, and you are required to settle the invoices within 7 days from the date of the
                                invoice. We reserve the right to charge you for this additional service, and you have the option
                                to accept or decline the charges and not use the associated channel.
                                Upgrades and downgrades between subscription plans are allowed. Please note that downgrading may
                                result in the loss of certain features or capacity of the services that were available to you
                                before the downgrade. We will not be held liable for such loss. When upgrading or downgrading,
                                the new Subscription Fees become immediately applicable. In the case of an upgrade, the new
                                Subscription Fees for the current month will be charged on a pro-rated basis and must be paid by
                                these Terms of Use. Subsequent months will be charged in full based on the new Subscription
                                Fees, and any applicable credits will be adjusted accordingly.
                            </p></br>
                            <h3 class="text-xl font-semibold">
                                WHATSAPP BUSINESS API
                            </h3>
                            <p>The user acknowledges and agrees that Chatboat has partnered with WhatsApp Business Service
                                Providers to offer the services through the platform. The user understands that the platform is
                                integrated with WhatsApp API, and certain registration data may be shared with WhatsApp.
                                Chatboat disclaims any liability arising from the user's use of WhatsApp API through the
                                platform. The user agrees to adhere to WhatsApp's terms and conditions for the usage of WhatsApp
                                Business, which can be found in the following links:</p>
                            <p>- WhatsApp Business Policy: https://www.whatsapp.com/legal/business-policy</br>
                                - WhatsApp Business API: https://www.whatsapp.com/business/api/</br>
                                - WhatsApp Commerce Policy: https://www.whatsapp.com/legal/commerce-policy/</br>
                                - WhatsApp API Rate Limits: https://developers.facebook.com/docs/whatsapp/api/rate-limits
                            </p>
                            <p>The user understands that WhatsApp may update its policies, including the WhatsApp Business
                                Policy, without notice. By continuing to use the WhatsApp Business Products through the Chatboat
                                platform after such changes, the user consents to the updated policies.</p>
                            <p>The user represents and warrants that they are not in violation of the WhatsApp Commerce Policy
                                and do not fall under any of the restricted industries outlined in WhatsApp's commercial policy.
                                The user acknowledges that WhatsApp Business may impose limits on the number of messages that
                                can be sent per day, as per its policy.</p>
                            <p>Furthermore, WhatsApp has the discretion to review, approve, or reject any WhatsApp Message
                                Templates submitted by the user at any time.</p>
                            <p>WhatsApp does not provide a way to be notified when a WhatsApp user has blocked the sender or to
                                retrieve a list of blocked users.</p>
                            <p>Violation of WhatsApp's policies may result in the suspension of the user's WhatsApp account.
                                WhatsApp has the absolute discretion to limit or remove access to the WhatsApp Business API and
                                other WhatsApp Business Products if the user receives excessive negative feedback, causes harm
                                to WhatsApp or its users, or violates the terms or policies set by WhatsApp. If WhatsApp
                                terminates the user's account for policy violations, the user and their organization may be
                                prohibited from future use of WhatsApp Business API and other WhatsApp Business Products.</p>
                            <p>Chatboat takes no responsibility for any violations of WhatsApp's policies, and any additional
                                charges arising from such violations will be borne by the user.</p>
                            <p>Once registered on the Chatboat platform, the user cannot reuse the WhatsApp number registered
                                with Chatboat on other similar platforms or the WhatsApp Business App or WhatsApp mobile app.
                            </p></br>
                            <h3 class="text-xl font-semibold">
                                WHATSAPP MESSAGE TEMPLATE
                            </h3>
                            <p>WhatsApp retains the authority to modify acceptable message types and related policies at their
                                sole discretion, without prior notice. As a user, you are only permitted to initiate chats using
                                approved WhatsApp Message Templates, which are subject to applicable pricing. It is important to
                                ensure that any WhatsApp Message Templates comply with WhatsApp's terms and are used solely for
                                their designated purpose. WhatsApp reserves the right to review, approve, and reject any
                                WhatsApp Message Template at any given time.
                                You must acknowledge your responsibility for the variable costs associated with WhatsApp Message
                                Templates, which will be billed by us. Starting from 1st February 2022, WhatsApp has implemented
                                conversation-based pricing. For detailed information about the pricing structure, please refer
                                to the following link: https://chatboat.in/chatboat/#pricing
                            </p></br>
                            <h3 class="text-xl font-semibold">
                                SERVICE ACCESS AND USE ON THE PLATFORM
                            </h3>
                            <p>You are prohibited from using the Platform or its Services to host, display, upload, modify,
                                publish, transmit, store, update, or share any information that falls under the following
                                categories:</p>
                            <p>1) Information that belongs to someone else and you do not have the right to use.</br>
                                2) Defamatory, obscene, pornographic, pedophilic, invasive of privacy, insulting, harassing, or
                                racially or ethnically objectionable content.</br>
                                3) Content that is harmful to children.</br>
                                4) Content that infringes upon patents, trademarks, copyrights, or any other proprietary
                                rights.</br>
                                5) Content that violates any existing laws or regulations.</br>
                                6) Misleading information that intentionally deceives or misleads recipients, or false
                                information presented as facts.</br>
                                7) Impersonation of another person.</br>
                                8) Content that threatens the unity, integrity, defence, security, or sovereignty of India,
                                friendly relations with other countries, public order, or incites the commission of a criminal
                                offence.</br>
                                9) Content that contains software viruses or any other computer code designed to disrupt,
                                destroy, or limit the functionality of computer resources.</br>
                                10) Patently false or misleading information created or published to mislead or harass others
                                for financial gain or causing harm.</br>
                                11) Unlawful information that is prohibited by current laws related to the sovereignty and
                                integrity of India, state security, friendly relations with other countries, public order,
                                decency or morality, contempt of court, defamation, incitement to offences, or any information
                                that is prohibited under existing laws.</br>
                                12) Any private information of third parties, including addresses, phone numbers, email
                                addresses, or any personally identifiable information.</br>
                            </p>
                            <p>You are prohibited from using the Platform in the following ways:</p>
                            <p>1) Uploading, posting, emailing, or transmitting any material that contains software viruses or
                                any other computer code, files, or programs designed to interrupt, destroy, or limit the
                                functionality of computer software, hardware, or telecommunications equipment.</br>
                                2) Disrupting the normal flow of dialogue or negatively affects other users' ability to engage
                                in real-time exchanges or utilize the service.</br>
                                3) Interfering with or disrupting the Platform, servers, or networks connected to the Platform,
                                or disobeying any requirements, procedures, policies, or regulations of connected networks.</br>
                                4) Violating any applicable local, state, national, or international law, including regulations
                                set by regulatory authorities or securities exchanges.</br>
                                5) Engaging in fraudulent or unlawful acts, whether related to third-party providers or
                                otherwise.</br>
                                6) Unauthorized copying, modification, adaptation, reverse engineering, disassembly,
                                decompilation, or creation of derivative works of the Services or any content included
                                therein.</br>
                                7) Distributing, licensing, transferring, or selling the Services or any derivative works.</br>
                                8) Using the Services for commercial purposes without express written consent, including
                                advertising, solicitation, or spamming.</br>
                                9) Incorporating the Services into other programs or products without authorization.</br>
                                10) Impersonating or misrepresenting affiliation with any person.</br>
                                11) Infringing upon any patent, trademark, trade secret, copyright, or other proprietary rights
                                of any party.</br>
                                12) Attempting to access or use another user's, patient's, or practitioner's account, service,
                                or system, or creating a false identity.</br>
                                13) Selling advertising, sponsorships, or promotions on the Service or Content, unless
                                specifically allowed by Us, or on any page containing Content from the Service.</br>
                            </p>
                            <p>In addition to the above, you must also comply with our Privacy Policies, which may be updated
                                from time to time. A copy of our Privacy Policies is available on our Platform.</p>
                            <p>You are solely responsible for the information you transmit or share through the Platform. Your
                                communications through the Platform are encrypted by WhatsApp Business, and we do not have
                                access to those communications. If you fail to comply with these Terms of Use, we may terminate
                                your registration and/or prevent your access to the Platform and its services without prior
                                notice.</p>
                            <p>The Platform may include third-party content or hyperlinks to third-party websites or services,
                                including advertisements. We do not control or endorse any third-party content, and we are not
                                responsible for its availability, accuracy, or the products and services offered. We are not
                                liable for any third-party content transmitted through the Platform. Third-party content is not
                                monitored, censored, or edited by us, and any actions you take about such content are your
                                responsibility. Before using any third-party content, you should read and understand its
                                associated privacy policy and terms of use</p>
                            <p>By using the Platform, you release and hold us harmless from any liability arising from your use
                                of third-party communications and content. This includes any losses or damages incurred in your
                                dealings with third parties or as a result of the presence or functioning of third-party content
                                on the Platform. It is your responsibility to evaluate the content and usefulness of information
                                obtained from third-party sources.</p></br>
                            <h3 class="text-xl font-semibold">
                                PERSONAL DATA PROTECTION
                            </h3>
                            <p>Our obligation regarding the use of Personal Data is limited to the purpose for which it was
                                collected.
                                Personal Data: By this Terms of Use, if we receive your Registration Data while providing
                                Chatboat Services, we agree to the following:
                            </p>
                            <p>- We will not disclose or use any of your Registration Data for any purpose other than necessary
                                to fulfil our obligations under this agreement.</br>
                                - We will not disclose your Personal Data to any third party, including our third-party service
                                providers, without your prior written consent and subject to the requirements outlined in this
                                clause.</br>
                                - We will implement administrative, technical, and physical safeguards to prevent unauthorized
                                use or disclosure of your Personal Data.</br>
                                - Upon your request, we will provide information regarding our privacy and information security
                                systems, policies, and procedures to fulfil our obligations under applicable laws and
                                regulations.</br>
                                - If there is any actual or suspected theft, unauthorized use, or disclosure of your
                                Registration Data, we will promptly investigate, correct the causes, remediate the effects, and
                                notify you of such events.</br>
                                - Once any event described in the above clause is discovered, we will provide you with a notice
                                and any requested information and assistance on time.
                            </p></br>
                            <h3 class="text-xl font-semibold">
                                RIGHTS TO INTELLECTUAL PROPERTY AND PLATFORM LICENCE
                            </h3>
                            <p>The Platform, products, and Services, including all content, are protected by intellectual
                                property rights owned by us or our affiliates or licensors. This includes but is not limited to
                                text, graphics, logos, images, audio, software, and technology used on the Platform. We and our
                                licensors retain all rights not expressly granted in these Terms of Use.</p>
                            <p>All software used on the Platform is our intellectual property and is protected by Indian and
                                international copyright laws.</p>
                            <p>Subject to these Terms of Use and within the limits permitted by us, we grant you a limited,
                                non-exclusive, revocable, royalty-free, non-transferable, non-assignable, non-sublicensable
                                right and license to access and make personal use of the Platform and the Services provided on
                                the Platform. This license does not include the right to redistribute, resell, or commercially
                                use the Platform.</p>
                            <p>You are prohibited from re-utilizing the Services of our Platform or systematically extracting
                                any part of the content or using any robots, data mining, or extraction tools for reutilization.
                                Additionally, you cannot create or publish anything that features parts of our Platform without
                                our prior written permission, including our Services and their prices.</p>
                            <p>The trademarks "Chatboat" and "Infomedia," along with their logos and local language variants,
                                are owned by Infomedia and are protected trademarks. Unless expressly provided in these Terms of
                                Use or authorized in writing by us, you are not permitted to use any Infomedia Marks or our
                                intellectual property in any press release, advertisement, promotional material, or media,
                                whether written, oral, electronic, visual, or otherwise.</p>
                            <p>References to other parties trademarks on the Platform, including our payment service providers
                                and other service providers, are for identification purposes only and do not indicate their
                                approval of the Platform or its Services. These Terms of Use do not grant you any right to use
                                the trademarks of these third parties.</p></br>
                            <h3 class="text-xl font-semibold">
                                REPRESENTATIONS AND WARRANTIES
                            </h3>
                            <p>
                                You represent and warrant the following:
                            </p>
                            <p>1) You have the legal capacity and authority to enter into this Terms of Use and agree to be
                                bound by its terms and conditions.</br>
                                2) You will not misuse or exceed the intended functionality of the Services.</br>
                                3) You will not attempt to gain unauthorized access to the Services or any connected networks,
                                servers, or computer systems.</br>
                                4) You will not use the Services in a way that may damage or impair the Services or our
                                underlying systems and security.</br>
                                5) You will not use the Services for any unlawful purposes or to promote illegal activities,
                                including copyright infringement or data theft.</br>
                                6) You will not use any intellectual property, including copyrighted content displayed on the
                                Platform, for personal or third-party gain without our explicit consent.</br>
                                7) You will not modify, adapt, translate, or reverse engineer any part of the Services,
                                including creating a shadow site or mirroring the Services.</br>
                                8) If your Mobile Contact Number is listed in the Do Not Disturb/National Consumer Preference
                                Register List of the Telecom Regulatory Authority of India (TRAI), you will promptly notify us
                                after primary registration.</br>
                                9) You understand that any calls or text messages you receive from us on your Mobile Contact
                                Number are not unsolicited.</br>
                                10) You will not take any actions or omissions that would create liability for us or cause us to
                                lose the services of our internet service providers (ISPs) or other partners, suppliers,
                                contractors, or vendors.</br>
                            </p></br>
                            <h3 class="text-xl font-semibold">
                                CONFIDENTIALITY
                            </h3>
                            <p>Each party acknowledges and agrees to the following regarding Confidential Information:</p>
                            <p>1) All Confidential Information remains the exclusive property of the party disclosing it
                                (Disclosing Party).</br>
                                2) The receiving party (Receiving Party) shall only use the Confidential Information to fulfil
                                the terms of the agreement.</br>
                                3) The Receiving Party shall not disclose the Confidential Information to any third party,
                                except to its employees, officers, contractors, agents, and service providers who need to know
                                the information for the agreement. These permitted individuals must be bound in writing by
                                obligations of confidentiality and non-use that are no less protective than those stated in this
                                agreement.</br>
                                4) Upon termination of the agreement or at the request of the Disclosing Party, the Receiving
                                Party shall return or destroy all Confidential Information, subject to applicable law and the
                                internal record-keeping requirements of the Receiving Party.</br>
                                5) The definition of Confidential Information does not include information that:</br>
        
                                &nbsp; a. Becomes publicly known without any action or omission by the Receiving Party.</br>
                                &nbsp;b. Was already in the possession of the Receiving Party before signing up on the Account
                                without an obligation of confidentiality.</br>
                                &nbsp;c. Is disclosed to the Receiving Party by a third party without any confidentiality
                                obligation.</br>
                                &nbsp;d. Is required to be disclosed by applicable law, court order, subpoena, or governmental
                                authority. In such cases, the Receiving Party must notify the Disclosing Party and provide them
                                with a reasonable opportunity to contest or limit the required disclosure.
                            </p></br>
                            <h3 class="text-xl font-semibold">
                                DISCLAIMER OF WARRANTIES
                            </h3>
                            <p>Your use of the Platform is at your own risk. The Platform is provided on an "as is" basis
                                without warranties of any kind, either express or implied. We do not make any warranties or
                                representations regarding the accuracy, currency, completeness, or reliability of any services
                                provided through the Platform or any third-party services linked to the Platform. We assume no
                                liability or responsibility for any errors, mistakes, or inaccuracies of service, personal
                                injury, property damage, or any nature resulting from your access to and use of the Platform. We
                                also do not warrant that:</br>
        
                                - Your use of the services will meet your requirements.</br>
                                - Any information obtained through your use of the services will be accurate or reliable.</br>
                                - Any defects in the operation or functionality of any software provided as part of the services
                                will be corrected.
                            </p>
                            <p>We Do Not Warrant, Endorse, Guarantee, or Assume Responsibility for Any Service Advertised or
                                Offered by a Third Party Through the Platform, Including Any Hyperlinked Website or Featured
                                Banner or Advertising. We Will Not Be a Party to or Responsible for Monitoring Any Transaction
                                Between You and Third-party Providers of Products or Services, Except as Provided Herein. You
                                Need to Exercise Caution and Use Your Best Judgment When Engaging in Transactions With
                                Third-party Providers.</p>
                            <p>Furthermore, Neither We Nor Our Affiliates or Licensors Warrant That Access to the Platform Will
                                Be Uninterrupted, Error-free, or Always Accessible. We Do Not Guarantee the Timeliness,
                                Accuracy, Reliability, Completeness, or Information or Materials Provided Through the Use of the
                                Platform. We Are Not Responsible for the Conduct of Any User, Whether Online or Offline. We Do
                                Not Warrant That the Platform is Free From Viruses, Worms, Trojan Horses, or Other Harmful
                                Components, and We Cannot Guarantee the Security of Any Personal Information Provided by You. We
                                May Change, Suspend, Withdraw, or Restrict the Availability of All or Any Part of Our Platform
                                for Business and Operational Reasons at Any Time Without Notice.</p></br>
                            <h3 class="text-xl font-semibold">
                                LIMITATION OF LIABILITY
                            </h3>
                            <p>Under No Circumstances Will We, Our Affiliates, Licensors, or Any of Their Agents, Employees,
                                Officers, Directors, Corporate Partners, or Participants Be Held Responsible for Any Direct,
                                Indirect, Incidental, Consequential, Special, or Exemplary Damages That May Arise From Your Use
                                of or Inability to Use the Platform. Even if You Have Been Advised of the Possibility of Such
                                Damages, This Includes but is Not Limited to Any Loss of Profit (Whether Incurred Directly or
                                Indirectly), Loss of Goodwill, Loss of Opportunity, or Any Loss of Data You May Suffer.</p>
                            <p>We Shall Not Be Held Liable for Any Loss or Damage That You May Experience as a Result of the
                                Completeness, Accuracy, or Existence of Any Advertising, or Due to Any Relationship or
                                Transaction Between You and Any Advertiser or Sponsor Whose Advertising Appears on the Service.
                                We Are Not Responsible for Any Changes We May Make to the Services, or for Any Permanent or
                                Temporary Cessation in the Provision of the Services (or Any Features Within the Services).
                                Additionally, We Cannot Be Held Responsible for the Deletion, Corruption, or Failure to Store
                                Any Content and Other Communication Data Maintained or Transmitted Through Your Use of the
                                Services. Furthermore, Any Loss or Damage Resulting From Your Failure to Provide Us With
                                Accurate Account Information or to Keep Your Password or Account Details Secure and Confidential
                                is Not Our Liability.</p>
                            <p>We Hold No Responsibility Towards You for Any Loss of Profit, Loss of Business, Loss of Goodwill
                                or Business Reputation, Business Interruption, or Loss of Business Opportunity.</br>
                                We Shall Not Be Held Liable for Any Damages That Could Have Been Avoided Had You Followed Our
                                Advice to Apply a Free Update Offered to You, or if the Damage Resulted From Your Failure to
                                Correctly Follow Installation Instructions or Meet the Minimum System Requirements Advised by
                                Us.
                            </p>
                            <p>You Are Accountable for Any Mobile Charges That May Be Incurred From Your Usage of Our Service,
                                Including Text Messaging and Data Charges.
                                To the Maximum Extent Permitted by Law, Any Dispute You Encounter With a Third Party Arising
                                From Your Use of the Services, Such as a Carrier, Copyright Owner, or Other User, is Solely
                                Between You and That Third Party. You Hereby Release Us and Our Affiliates From Any and All
                                Claims, Demands, and Damages (Both Actual and Consequential) of Every Kind and Nature, Known and
                                Unknown, Arising From or in Connection With Such Disputes.</p></br>
                            <h3 class="text-xl font-semibold">
                                INDEMNITY
                            </h3>
                            <p>By Accepting These Terms, You Agree to Indemnify, Defend, and Hold the Us, Our Affiliates,
                                Licensors, Distributors, Agents, Representatives, and Other Authorized
                                Users/patients/practitioners Harmless From Any and All Losses, Damages, Liabilities, and Costs
                                That May Arise From or Be Connected to:</br>
        
                                1) Your Use or Access to the Platform.</br>
                                2) Your Breach of Any Terms, Obligations, Representations, and Warranties Stated in This Terms
                                of Use.</br>
                                3) Any Claim That the Provision or Use of the Services Infringes Upon Any Rights of a Third
                                Party.</br>
                                4) Your Violation of Applicable Laws.</p>
                            <p>Please Note That Nothing in These Terms of Use Shall Exclude or Limit Our Liability for Any
                                Liability That Cannot Be Excluded or Limited Under the Applicable Laws in Force in India. Your
                                Statutory Rights as a User Remain Unaffected by These Terms of Use.</p></br>
                            <h3 class="text-xl font-semibold">
                                GENERAL
                            </h3>
                            <p>All notices should be provided to us via email or to you at the email or postal address you have
                                provided.
                                Any waiver of our rights or remedies under these Terms of Use will only be effective if it is in
                                writing, executed by our duly authorized representative, and applicable only to the specific
                                circumstances for which it is granted. Our failure to exercise or enforce any right or remedy
                                under these Terms of Use shall not be considered a waiver of such right or remedy, nor shall it
                                prevent any future exercise or enforcement of such right or remedy. No partial or single
                                exercise of any right or remedy shall limit or restrict the further exercise of such right,
                                remedy, or other rights and remedies.
                            </p>
                            <p>These Terms of Use, together with our Privacy Policies referenced herein, constitute the entire
                                agreement between the parties concerning the subject matter.
                                The headings in these Terms of Use are for convenience purposes only and do not have any legal
                                or contractual effect. The terms "including" and "includes" mean "including without limitation."
                            </p>
                            <p>
                                The provisions of these Terms of Use shall be interpreted harmoniously with each other, as well
                                as applicable laws (including the laws of the jurisdiction of the user) and shall be upheld to
                                the fullest extent permitted by applicable laws. Furthermore, the provisions in these Terms of
                                Use shall be enforceable independently, and if any provision is held to be invalid, it shall not
                                affect the validity of other provisions. If any provision of these Terms of Use is found to be
                                invalid or unenforceable, the other provisions shall remain unaffected (to the maximum extent
                                permissible), and the invalid or unenforceable provision shall be modified to make it valid and
                                enforceable to the fullest extent permitted by applicable laws. Additionally, if any provision
                                is void but would be valid if certain parts were deleted, the provision shall be applied with
                                such modifications as necessary to make it valid.
                            </p>
                            <p>You confirm that you do not have an employment, contractor, agency, or partnership relationship
                                with us. We are solely providing you with the services upon your request. Furthermore, you are
                                acting either on your behalf or on behalf of another person, as stated in these Terms of Use.
                            </p>
                            <p>These Terms of Use, as well as any dispute or claim arising out of or relating to them (including
                                non-contractual disputes or claims), shall be governed by and construed by the prevailing laws
                                in India. You agree that the courts in Ahmedabad, Gujarat, shall have exclusive jurisdiction to
                                settle any dispute or claim arising from or related to these Terms of Use.</p>
        
                    </div>
                </div>
            </div>
        </div>
       </div>  
     </section> 
@endsection

